version: '3'
services:
  app:
    image: my-python-app:latest
    environment:
      - OPERATOR=+
      - NUMBER1=5
      - NUMBER2=3
      - CHOICE=1
    ports:
      - "80:5000"
    restart: always
